module.exports = [
	{type: "PLAYING", text: "with emotes!"},
	{type: "PLAYING", text: "with cats!"},
	{type: "PLAYING", text: "with cheat codes."},
	{type: "WATCHING", text: "the snow fall."},
	{type: "WATCHING", text: "cat videos."},
	{type: "WATCHING", text: "the sunset."},
	{type: "WATCHING", text: "the waves."},
	{type: "WATCHING", text: "the sunrise."},
	{type: "WATCHING", text: "the hummingbirds."},
	{type: "WATCHING", text: "the stars."},
	{type: "WATCHING", text: "the campfire."},
	{type: "LISTENING", text: "raindrops."},
	{type: "LISTENING", text: "waves crash."},
	{type: "LISTENING", text: "an old record."},
	{type: "LISTENING", text: "a whisper."},
];
